apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2024-04-14T03:40:05Z","generation":1,"labels":{"app":"consumingrest"},"name":"consumingrest","namespace":"default","resourceVersion":"18582","uid":"39d1ddb6-c62b-4f30-b92b-087a9ba7962e"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"consumingrest"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"consumingrest"}},"spec":{"containers":[{"env":[{"name":"QUOTERS_BASE_URL","value":"http://quoters:8080"}],"image":"akhargha/consumingrest","imagePullPolicy":"Always","name":"consumingrest","ports":[{"containerPort":5000}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-04-14T03:40:06Z","lastUpdateTime":"2024-04-14T03:40:06Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2024-04-14T03:40:05Z","lastUpdateTime":"2024-04-14T03:40:06Z","message":"ReplicaSet \"consumingrest-5d7f75b964\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-04-14T03:40:05Z"
  generation: 2
  labels:
    app: consumingrest
  name: consumingrest
  namespace: default
  resourceVersion: "18959"
  uid: 39d1ddb6-c62b-4f30-b92b-087a9ba7962e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: consumingrest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consumingrest
    spec:
      containers:
      - env:
        - name: QUOTERS_BASE_URL
          value: http://quoters:8080
        image: akhargha/consumingrest
        imagePullPolicy: Always
        name: consumingrest
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-14T03:40:06Z"
    lastUpdateTime: "2024-04-14T03:40:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-14T03:40:05Z"
    lastUpdateTime: "2024-04-14T03:44:24Z"
    message: ReplicaSet "consumingrest-75895b6cc4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
